### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by o-lenczyk** [satyarth/pixelsort#11]
Hi
I got an error

```
$ python36 pixelsort.py test.png 
Interval function:  threshold
Lower threshold:  0.25
Upper threshold:  0.8
Randomness:  0 %
Opening image...
Converting to RGBA...
Rotating image...
Getting data...
Getting pixels...
Determining intervals...
Defining intervals...
Traceback (most recent call last):
  File "pixelsort.py", line 56, in <module>
    main()
  File "pixelsort.py", line 31, in main
    intervals = argparams.interval_function(pixels, argparams)
  File "/home/clone/repos/pixelsort/interval.py", line 60, in threshold
    if util.lightness(pixels[y][x]) < args.bottom_threshold or util.lightness(pixels[y][x]) > args.upper_threshold:
  File "/home/clone/repos/pixelsort/util.py", line 11, in lightness
    return rgb_to_hsv(pixel[0], pixel[1], pixel[2])[2] / 255.0  # For backwards compatibility with python2
TypeError: 'int' object is not subscriptable
```

**Comment by abetusk** [comment]
Could you provide a test image so that we can test this and reproduce this error?

**Comment by abetusk** [comment]
Vote to close as I (and others?) can't reproduce this error. If a test image and command is provided that can reproduce this error we can always re-open this issue or create a new one.

**Comment by BernardZhao** [comment]
Sounds good @abetusk
