### ISSUE TITLE
Mask is not rotated and potentially gives errors when rotate and mask are both specified

### ISSUE THREAD

**Issue by abetusk** [satyarth/pixelsort#19]
I get the following error when trying to use the mask on a rotated pixel sort image:

```
$ python3 pixelsort.py examples/image.jpg -i random -a 120 -c 20 -m examples/mask.png 
Traceback (most recent call last):
  File "pixelsort.py", line 81, in <module>
    main(parse_args())
  File "pixelsort.py", line 33, in main
    pixels = get_pixels(data, mask, input_img.size)
  File "pixelsort.py", line 62, in get_pixels
    if not (mask and mask[x, y] == constants.black_pixel):
IndexError: image index out of range
```

After adding the following line:

```
    mask = Image.open(args["mask"]).convert('RGBA').rotate(args["angle"], expand=True).load() if args["mask"] else None
```

I get the following image as I would expect:

![3vxZ7](https://user-images.githubusercontent.com/1406122/67833520-4251db80-fabb-11e9-88c8-5c44e1c395b8.png)

I'll submit a PR with the fix unless you get to it before I do.

**Comment by satyarth** [comment]
fixed in 3444f60
